# Generated by Django 4.2.13 on 2024-05-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0004_remove_doctor_availability_doctor_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
