# Generated by Django 4.2.13 on 2024-05-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0007_alter_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctorName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
