# Generated by Django 4.2.13 on 2024-05-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0008_appointment_doctorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='joined',
            field=models.BooleanField(default=False),
        ),
    ]
